Brickout1
 Brickout game
Python

Issue: 
error running in Notepad ++ Python 3.7.2 TK 8.6.8
Error code:
Traceback (most recent call last):
  File "C:\Users\Wednesday Addams\Documents\Source\Repos\Python\brickout-game\brickout-game.py", line 18, in <module>
    import pygame
ModuleNotFoundError: No module named 'pygame'

## looks like pygame doesn't exist, maybe it's in the .zip with all of the python programs ##